---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-v2
  template:
    metadata:
      labels:
        app: myapp-v2

    spec:
      containers:
      - name: myapp-v2
        image: arjunmishra/app-deploy-k8s:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-v2
spec:
  selector:
    app: myapp-v2
  loadBalancerIP: 35.215.0.250
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
